export const REGISTER_DOCTOR = "REGISTER_DOCTOR"
export const REGISTER_SUCCES_DOCTOR = "REGISTER_SUCCES_DOCTOR"
export const REGISTER_FAIL_DOCTOR= "REGISTER_FAIL_DOCTOR"

export const LOGIN_DOCTOR = "LOGIN_DOCTOR"
export const LOGIN_SUCCES_DOCTOR = "LOGIN_SUCCES_DOCTOR"
export const LOGIN_FAIL_DOCTOR= "LOGIN_FAIL_DOCTOR" 

export const GET_PROFILE_DOCTOR = "GET_PROFILE_DOCTOR"
export const GET_PROFILE_SUCCES_DOCTOR = "GET_PROFILE_SUCCES_DOCTOR"
export const GET_PROFILE_FAIL_DOCTOR= "GET_PROFILE_FAIL_DOCTOR"

export const LOGOUT_DOCTOR = "LOGOUT_DOCTOR"
export const GET_ALL_DOCTORS="GET_ALL_DOCTORS"
export const FILTER_DOCTORS = "FILTER_DOCTORS"

export const GET_PEDIATRE = "GEt_PEDIATRE"
export const GET_GENYCO ="GET_GENYCO"
export const GET_DENTIST ="GET_DENTIST"